### ISSUE TITLE
pioupload.py: UploadToDisk does not honor board needing .hex instead of .bin

### ISSUE THREAD

**Issue by rph8** [platformio/platformio#315] opened 2015-10-30 20:22 UTC
I am using the Seeed Arch BLE board with firmware v0221 (2015-02-03) and it requires a .hex file to be copied to the "MBED" virtual USB disk.
The problem is that in /platformio/builder/tools/pioupload.py in lines 97 and 98 there is differentiation for .hex. Instead it reads:
```
    copyfile(join(env.subst("$BUILD_DIR"), "firmware.bin"),
             join(env.subst("$UPLOAD_PORT"), "firmware.bin"))
```

I changed this to 
```
    copyfile(join(env.subst("$BUILD_DIR"), "firmware.hex"),
             join(env.subst("$UPLOAD_PORT"), "firmware.hex"))
```

in my local installation, but this is clearly not a scalable solution.
In fact I have another board out of the same series, but with a different MCU, the Seeed Arch Max which does required .bin files.

I would propose a proper patch, but don't know the platformio code well enough yet.

(Used version 2.3.4.)

**Comment by ivankravets** [comment] 2015-11-02 11:15
Duplicate of https://github.com/platformio/platformio/issues/316

**Closed by ivankravets** 2015-11-02 11:15 UTC
