### ISSUE TITLE
Simpler windows installation instructions

### ISSUE THREAD

**Issue by pelikhan** [platformio/platformio#36] opened 2014-12-19 12:20 UTC
Chocolatey uses powershell to install download their install script on windows. You could do the same... 

    @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin

Or you could have users install Chocolatey then be a package of this environment. Keep up the great work!

**Comment by pelikhan** [comment] 2015-01-03 19:40
Unfortunately, the script fails on some Windows machine and I don't why precisely. It fails when trying to update the path.

**Comment by pelikhan** [comment] 2015-01-03 20:05
Out of curiosity, why does scon need the --egg option?

**Comment by ivankravets** [comment] 2015-01-03 20:23
> Out of curiosity, why does scon need the --egg option?

SCons doesn't support `pip` yet :( See discussion: 
https://bitbucket.org/scons/scons/pull-request/113/fix-for-bug-2769-which-should-allow-scons

**Comment by ivankravets** [comment] 2015-01-03 20:23
> Unfortunately, the script fails on some Windows machine and I don't why precisely. It fails when trying to update the path.

Can you give me a traceback?

**Comment by pelikhan** [comment] 2015-01-06 03:23
No access to that machine anymore unfortunately.

**Comment by dave93cab** [comment] 2015-04-29 06:04
I had the hang on updating paths on my work laptop earlier which may have some restrictions though I have full administrator privileges and was able to update $PATH manually. 

Ivan, 

I can get anything you need from that machine of you let me know what and how

**Comment by ivankravets** [comment] 2015-04-29 12:16
@dave93cab Have you tried to run ``cmd`` with Administrative privileges?

**Comment by dave93cab** [comment] 2015-04-30 04:05
Hi Ivan,

When I installed platformio and the script ran I just updated the PATH manually and installed with pip. It was only that I saw this issue I commented and I just tried the script on this laptop again, running cmd with administrator privileges and it hangs on the path step.. 

![image](https://cloud.githubusercontent.com/assets/11580510/7406195/0d13866a-eec4-11e4-8e91-219ad85815f1.png)

Let me know if theres anything I can give you to diagnose if you want or have time to :)

**Comment by ivankravets** [comment] 2015-04-30 10:43
Does ``pip`` work for you? If yes, just install PlatformIO via:
```shell
pip install platformio
pip install --egg http://sourceforge.net/projects/scons/files/latest/download
```

**Comment by dave93cab** [comment] 2015-04-30 13:39
I got it installed fine, I just wanted to let you know that the issue @pelikhan reported with the script is not isolated to him only :)

**Comment by ivankravets** [comment] 2015-04-30 15:10
@dave93cab I got you! Sorry.

@valeros Please contact with @dave93cab and try to reproduce this error https://github.com/platformio/platformio/issues/36#issuecomment-67737594

**Comment by ivankravets** [comment] 2015-09-05 20:41
@PlatformIO 2.3.0 has been released with simplified installation procedure. Just single command:
```shell
pip install platformio
```

No additional steps, no special installation scripts! Just one command! :+1: 

If you still have problems with PlatformIO installation, please reopen this issue.

**Closed by ivankravets** 2015-09-05 20:41 UTC
Labels: bug

**Comment by kalineBr** [comment] 2018-01-17 18:38
Hi @pelikhan 
That command doesn't works to me:

@powershell -NoProfile -ExecutionPolicy unrestricted -Command "((new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/ivankravets/platformio/master/scripts/get-platformio.py','get-platformio.py'));(New-Object -com Shell.Application).ShellExecute('python', 'get-platformio.py')"
 Can you help me? Because I tried install platformio core using the script in windows 10 x64, althought failed. The picture below:


![erro](https://user-images.githubusercontent.com/31135896/35060198-cfd523bc-fba4-11e7-985c-2d2458944fca.PNG)

**Comment by ivankravets** [comment] 2018-01-17 23:22
@kalineBr something is wrong with SSL certificates. 

Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```
