### ISSUE TITLE
How can i use esp8266-rtos-sdk with platformio

### ISSUE THREAD

**Issue by wuwx** [platformio/platformio#681] opened 2016-06-02 05:01 UTC
platformio‘s sdk-esp8266 use esp8266-nonos-sdk
but how can i use esp8266-rtos-sdk with platformio
thanks :)

**Comment by ivankravets** [comment] 2016-06-02 09:50
Duplicate of https://github.com/platformio/platformio/issues/402

**Closed by ivankravets** 2016-06-02 09:50 UTC
Labels: duplicate
