### ISSUE TITLE
esp-open-sdk and/or esp-open-rtos

### ISSUE THREAD

**Issue by MrDadaGuy** [platformio/platformio#593] opened 2016-03-23 14:24 UTC
Feature Request:

Please implement [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) and/or [esp-open-rtos](https://github.com/SuperHouse/esp-open-rtos) support.

Thanks for a great product!!

**Comment by ivankravets** [comment] 2016-03-24 13:18
Duplicate of #366 and #402.

**Comment by ivankravets** [comment] 2016-11-27 22:19
Moved to https://github.com/platformio/platform-espressif8266/issues/14

**Closed by ivankravets** 2016-11-27 22:19 UTC
Labels: feature, moved, vendor:espressif
