### ISSUE TITLE
ESP8266 OTA: Support real hostnames as upload_port

### ISSUE THREAD

**Issue by tfohlmeister** [platformio/platformio#809] opened 2016-10-16 22:54 UTC
**ESP8266 OTA Feature Request**
I was wondering why the OTA `upload_port` option only supports fixed IPs or *.local hostnames. I use mDNS on all my ESPs but the mentioned restriction makes it very hard to use OTA flashing in mixed network environments whereas hostnames end in e.g. *.lan and the *.local hostname is not available because the ESP is connected to a different network than the programmer.

Is there any particular reason for this restriction? Shouldn't it be very easy to implement a proper name resolution?

**Comment by ivankravets** [comment] 2016-10-17 11:24
Duplicate of https://github.com/platformio/platformio/issues/463

**Closed by ivankravets** 2016-10-17 11:24 UTC
Labels: duplicate
