### ISSUE TITLE
Request library by name ?

### ISSUE THREAD

**Issue by glelouet** [platformio/platformio#538] opened 2016-02-25 13:38 UTC
This is actually a request/discussion :
 > PlatformIO, version 2.8.4

if I specify a lib by name :
 > lib_install = OneWire

I get a 
 > ValueError: invalid literal for int() with base 10: 'OneWire'

Is it possible to allow names of libs ?  I know the `lib_use` option does it already but it also needs the Id of the lib and is more "priority-oriented" request than lib_install.

**Comment by ivankravets** [comment] 2016-02-25 13:53
Duplicate of https://github.com/platformio/platformio/issues/414

**Closed by ivankravets** 2016-02-25 13:53 UTC
Labels: duplicate
