### ISSUE TITLE
Can't upload to Arduino Zero on programming USB port

### ISSUE THREAD

**Issue by fraimondo** [platformio/platformio#828] opened 2016-11-15 11:14 UTC
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Development Platform. All issues related to Development Platform should be reported to appropriate repository. Search it using link below
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: MacOS Sierra

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.1.0

### Description of problem
Can't upload if a configure the board as `zero`

#### Steps to Reproduce

1. Create a project
2. Configure board as `zero`
3. Try to upload

### Actual Results
It hangs with a terminal like this:
```Open On-Chip Debugger 0.9.0-gd4b7679 (2015-06-10-19:16)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'swd'
adapter speed: 500 kHz
adapter_nsrst_delay: 100
cortex_m reset_config sysresetreq
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : CMSIS-DAP: FW Version = 02.01.0157
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 1 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 500 kHz
Info : SWD IDCODE 0x0bc11477
Info : at91samd21g18.cpu: hardware has 4 breakpoints, 2 watchpoints 
```

### Expected Results
A terminal like this:
```
Open On-Chip Debugger 0.9.0-gd4b7679 (2015-06-10-19:16)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'swd'
adapter speed: 500 kHz
adapter_nsrst_delay: 100
cortex_m reset_config sysresetreq
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : CMSIS-DAP: FW Version = 02.01.0157
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 1 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 500 kHz
Info : SWD IDCODE 0x0bc11477
Info : at91samd21g18.cpu: hardware has 4 breakpoints, 2 watchpoints
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x81000000 pc: 0x00000858 msp: 0x200023a0
** Programming Started **
auto erase enabled
Info : SAMD MCU: SAMD21G18A (256KB Flash, 32KB RAM)
Warn : Adding extra erase range, 00000000 to 0x00001fff
wrote 24576 bytes from file .pioenvs/zero/firmware.bin in 3.507302s (6.843 KiB/s)
** Programming Finished **
** Verify Started **
verified 17508 bytes in 1.445675s (11.827 KiB/s)
** Verified OK **
** Resetting Target **
shutdown command invoked
```

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:zero]
platform = atmelsam
board = zero
framework = arduino
lib_extra_dirs = ../../../arduino_libs/
```

**Source file to reproduce issue:**
```cpp
Any
```

### Additional info
I managed to find where's the problem.

The command to run openOCD it's as follows:
```
~/.platformio/packages/tool-openocd/bin/openocd
-f arduino_zero.cfg 
-s /Users/fraimondo/.platformio/packages/tool-openocd/share/openocd/scripts 
-s /Users/fraimondo/.platformio/packages/tool-openocd/share/openocd/scripts/board 
-s /Users/fraimondo/.platformio/packages/framework-arduinosam/variants/arduino_zero/openocd_scripts 
-c "telnet_port disabled; program {{.pioenvs/zero/firmware.bin}} verify reset 0x2000; shutdown"
```

I checked with the official arduino IDE and one of the `-s` parameters is not there. So I tried running 
```
~/.platformio/packages/tool-openocd/bin/openocd
-f arduino_zero.cfg 
-s /Users/fraimondo/.platformio/packages/tool-openocd/share/openocd/scripts 
-s /Users/fraimondo/.platformio/packages/framework-arduinosam/variants/arduino_zero/openocd_scripts 
-c "telnet_port disabled; program {{.pioenvs/zero/firmware.bin}} verify reset 0x2000; shutdown"
```

And that works just fine.

**Comment by ivankravets** [comment] 2016-11-16 09:29
Duplicate of https://github.com/platformio/platformio/issues/805

**Closed** 2016-11-16 09:30 UTC
Labels: duplicate
