### ISSUE TITLE
Support for C++11 Libraries

### ISSUE THREAD

**Issue by sathibault** [platformio/platformio#638] opened 2016-04-29 11:11 UTC
The -std=c++11 may conflict with other platform libraries and cannot always be added to a project build_flags.  There should be some way for the library.json to be able to specify this.  I'm not sure just having an extra flags attribute in the library.json is sufficient since the base flags may already have some -std option.

**Comment by ivankravets** [comment] 2016-04-29 11:25
Duplicate of https://github.com/platformio/platformio/issues/289

**Closed by ivankravets** 2016-04-29 11:25 UTC
