### ISSUE TITLE
Installing shell commands on OSX

### ISSUE THREAD

**Issue by kommancs96** [platformio/platformio#495] opened 2016-02-03 16:01 UTC
I can't install shell commands on OSX. I use Atom IDE , and I have installed platformio-ide package, and I clicked on `Install shell commands` but nothing happened, and the `pio` and `platformio` commands don't work. Atom 1.4.3

**Comment by ivankravets** [comment] 2016-02-03 16:09
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/35

**Closed by ivankravets** 2016-02-03 16:09 UTC
Labels: duplicate
